// AUTO-GENERATED by Seefar from the live Supabase schema — do not edit by hand.
// Every Supabase query in this app is type-checked against the fields below.
// If the schema changes, re-run the Supabase integration to refresh this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      addresses: {
        Row: {
          city: string | null
          created_at: string | null
          id: string
          isDefault: boolean | null
          label: string | null
          lat: number | null
          lng: number | null
          street: string | null
          updated_at: string | null
          user_id: string
          zipCode: string | null
        }
        Insert: {
          city?: string | null
          created_at?: string | null
          id?: string
          isDefault?: boolean | null
          label?: string | null
          lat?: number | null
          lng?: number | null
          street?: string | null
          updated_at?: string | null
          user_id: string
          zipCode?: string | null
        }
        Update: {
          city?: string | null
          created_at?: string | null
          id?: string
          isDefault?: boolean | null
          label?: string | null
          lat?: number | null
          lng?: number | null
          street?: string | null
          updated_at?: string | null
          user_id?: string
          zipCode?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "addresses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      customization_options: {
        Row: {
          created_at: string | null
          customization_id: string
          id: string
          name: string
          price: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          customization_id: string
          id?: string
          name: string
          price?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          customization_id?: string
          id?: string
          name?: string
          price?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customization_options_customization_id_fkey"
            columns: ["customization_id"]
            isOneToOne: false
            referencedRelation: "customizations"
            referencedColumns: ["id"]
          },
        ]
      }
      customizations: {
        Row: {
          created_at: string | null
          id: string
          maxSelections: number | null
          menu_item_id: string
          name: string
          required: boolean | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          maxSelections?: number | null
          menu_item_id: string
          name: string
          required?: boolean | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          maxSelections?: number | null
          menu_item_id?: string
          name?: string
          required?: boolean | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customizations_menu_item_id_fkey"
            columns: ["menu_item_id"]
            isOneToOne: false
            referencedRelation: "menu_items"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_partners: {
        Row: {
          avatar: string | null
          created_at: string | null
          currentLocation_lat: number | null
          currentLocation_lng: number | null
          id: string
          name: string
          phone: string | null
          rating: number | null
          totalDeliveries: number | null
          updated_at: string | null
          vehicle: string | null
        }
        Insert: {
          avatar?: string | null
          created_at?: string | null
          currentLocation_lat?: number | null
          currentLocation_lng?: number | null
          id?: string
          name: string
          phone?: string | null
          rating?: number | null
          totalDeliveries?: number | null
          updated_at?: string | null
          vehicle?: string | null
        }
        Update: {
          avatar?: string | null
          created_at?: string | null
          currentLocation_lat?: number | null
          currentLocation_lng?: number | null
          id?: string
          name?: string
          phone?: string | null
          rating?: number | null
          totalDeliveries?: number | null
          updated_at?: string | null
          vehicle?: string | null
        }
        Relationships: []
      }
      favorites: {
        Row: {
          created_at: string | null
          id: string
          restaurant_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          restaurant_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          restaurant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      menu_categories: {
        Row: {
          created_at: string | null
          id: string
          name: string
          restaurant_id: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          name: string
          restaurant_id: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          name?: string
          restaurant_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "menu_categories_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      menu_items: {
        Row: {
          availability: boolean | null
          calories: number | null
          category: string | null
          category_id: string
          created_at: string | null
          description: string | null
          id: string
          image: string | null
          isPopular: boolean | null
          name: string
          price: number
          rating: number | null
          updated_at: string | null
        }
        Insert: {
          availability?: boolean | null
          calories?: number | null
          category?: string | null
          category_id: string
          created_at?: string | null
          description?: string | null
          id?: string
          image?: string | null
          isPopular?: boolean | null
          name: string
          price: number
          rating?: number | null
          updated_at?: string | null
        }
        Update: {
          availability?: boolean | null
          calories?: number | null
          category?: string | null
          category_id?: string
          created_at?: string | null
          description?: string | null
          id?: string
          image?: string | null
          isPopular?: boolean | null
          name?: string
          price?: number
          rating?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "menu_items_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "menu_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          created_at: string | null
          id: string
          menu_item_id: string
          order_id: string
          quantity: number
          specialInstructions: string | null
          totalPrice: number
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          menu_item_id: string
          order_id: string
          quantity?: number
          specialInstructions?: string | null
          totalPrice: number
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          menu_item_id?: string
          order_id?: string
          quantity?: number
          specialInstructions?: string | null
          totalPrice?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_menu_item_id_fkey"
            columns: ["menu_item_id"]
            isOneToOne: false
            referencedRelation: "menu_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          created_at: string | null
          createdAt: string | null
          deliveryAddress_id: string | null
          deliveryFee: number | null
          deliveryPartner_id: string | null
          discount: number | null
          estimatedDeliveryTime: string | null
          id: string
          promoCode: string | null
          rating: number | null
          restaurant_id: string
          scheduledTime: string | null
          status: string | null
          subtotal: number | null
          tax: number | null
          total: number | null
          updated_at: string | null
          userId: string
        }
        Insert: {
          created_at?: string | null
          createdAt?: string | null
          deliveryAddress_id?: string | null
          deliveryFee?: number | null
          deliveryPartner_id?: string | null
          discount?: number | null
          estimatedDeliveryTime?: string | null
          id?: string
          promoCode?: string | null
          rating?: number | null
          restaurant_id: string
          scheduledTime?: string | null
          status?: string | null
          subtotal?: number | null
          tax?: number | null
          total?: number | null
          updated_at?: string | null
          userId: string
        }
        Update: {
          created_at?: string | null
          createdAt?: string | null
          deliveryAddress_id?: string | null
          deliveryFee?: number | null
          deliveryPartner_id?: string | null
          discount?: number | null
          estimatedDeliveryTime?: string | null
          id?: string
          promoCode?: string | null
          rating?: number | null
          restaurant_id?: string
          scheduledTime?: string | null
          status?: string | null
          subtotal?: number | null
          tax?: number | null
          total?: number | null
          updated_at?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_deliveryAddress_id_fkey"
            columns: ["deliveryAddress_id"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_deliveryPartner_id_fkey"
            columns: ["deliveryPartner_id"]
            isOneToOne: false
            referencedRelation: "delivery_partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_methods: {
        Row: {
          created_at: string | null
          expiryDate: string | null
          id: string
          isDefault: boolean | null
          label: string | null
          lastFour: string | null
          type: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          expiryDate?: string | null
          id?: string
          isDefault?: boolean | null
          label?: string | null
          lastFour?: string | null
          type: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          expiryDate?: string | null
          id?: string
          isDefault?: boolean | null
          label?: string | null
          lastFour?: string | null
          type?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_methods_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      promos: {
        Row: {
          code: string
          created_at: string | null
          description: string | null
          discount: number
          discountType: string
          expiryDate: string | null
          id: string
          minOrderValue: number | null
          updated_at: string | null
          usageLimit: number | null
        }
        Insert: {
          code: string
          created_at?: string | null
          description?: string | null
          discount: number
          discountType: string
          expiryDate?: string | null
          id?: string
          minOrderValue?: number | null
          updated_at?: string | null
          usageLimit?: number | null
        }
        Update: {
          code?: string
          created_at?: string | null
          description?: string | null
          discount?: number
          discountType?: string
          expiryDate?: string | null
          id?: string
          minOrderValue?: number | null
          updated_at?: string | null
          usageLimit?: number | null
        }
        Relationships: []
      }
      recent_searches: {
        Row: {
          created_at: string | null
          id: string
          query: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          query: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          query?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recent_searches_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      restaurants: {
        Row: {
          created_at: string | null
          cuisine: string[] | null
          deliveryFee: number | null
          deliveryTime: string | null
          distance: string | null
          hours: string | null
          id: string
          image: string | null
          isOpen: boolean | null
          location_address: string | null
          location_lat: number | null
          location_lng: number | null
          minimumOrder: number | null
          name: string
          promoText: string | null
          rating: number | null
          reviewCount: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          cuisine?: string[] | null
          deliveryFee?: number | null
          deliveryTime?: string | null
          distance?: string | null
          hours?: string | null
          id?: string
          image?: string | null
          isOpen?: boolean | null
          location_address?: string | null
          location_lat?: number | null
          location_lng?: number | null
          minimumOrder?: number | null
          name: string
          promoText?: string | null
          rating?: number | null
          reviewCount?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          cuisine?: string[] | null
          deliveryFee?: number | null
          deliveryTime?: string | null
          distance?: string | null
          hours?: string | null
          id?: string
          image?: string | null
          isOpen?: boolean | null
          location_address?: string | null
          location_lat?: number | null
          location_lng?: number | null
          minimumOrder?: number | null
          name?: string
          promoText?: string | null
          rating?: number | null
          reviewCount?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      seefar_metadata: {
        Row: {
          app_id: string
          app_name: string
          created_at: string | null
          id: string
          seefar_origin: boolean | null
        }
        Insert: {
          app_id: string
          app_name: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Update: {
          app_id?: string
          app_name?: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Relationships: []
      }
      user_preferences: {
        Row: {
          created_at: string | null
          defaultAddressId: string | null
          defaultPaymentMethodId: string | null
          dietaryRestrictions: string[] | null
          id: string
          notificationsEnabled: boolean | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          defaultAddressId?: string | null
          defaultPaymentMethodId?: string | null
          dietaryRestrictions?: string[] | null
          id?: string
          notificationsEnabled?: boolean | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          defaultAddressId?: string | null
          defaultPaymentMethodId?: string | null
          dietaryRestrictions?: string[] | null
          id?: string
          notificationsEnabled?: boolean | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_preferences_defaultAddressId_fkey"
            columns: ["defaultAddressId"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_preferences_defaultPaymentMethodId_fkey"
            columns: ["defaultPaymentMethodId"]
            isOneToOne: false
            referencedRelation: "payment_methods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_preferences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar: string | null
          created_at: string | null
          email: string | null
          id: string
          joinedDate: string | null
          name: string | null
          phone: string | null
          totalOrders: number | null
          updated_at: string | null
        }
        Insert: {
          avatar?: string | null
          created_at?: string | null
          email?: string | null
          id: string
          joinedDate?: string | null
          name?: string | null
          phone?: string | null
          totalOrders?: number | null
          updated_at?: string | null
        }
        Update: {
          avatar?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          joinedDate?: string | null
          name?: string | null
          phone?: string | null
          totalOrders?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
